
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ADD DIV DUMP MUL PRINT READ SET SUB id numComando : '(' READ id ')'Comando : '(' PRINT Exp ')'Comando : '(' SET id Exp ')'Comando : '(' DUMP ')'Exp : '(' ADD Exp Termo ')'Exp : '(' SUB Exp Termo ')'Exp : TermoExp : '(' MUL Termo Fator ')'Termo : '(' DIV Termo Fator ')'Termo : FatorFator : '(' Exp ')'Fator : numFator : id"
    
_lr_action_items = {'(':([0,4,8,10,11,12,13,14,17,19,20,21,24,25,26,27,28,29,33,36,37,38,39,],[2,8,8,-7,-10,-12,-13,8,8,8,27,27,27,-11,27,8,33,33,8,-5,-6,-8,-9,]),'$end':([1,15,16,22,30,],[0,-4,-1,-2,-3,]),'READ':([2,],[3,]),'PRINT':([2,],[4,]),'SET':([2,],[5,]),'DUMP':([2,],[6,]),'id':([3,4,5,8,10,11,12,13,14,17,19,20,21,24,25,26,27,28,29,33,36,37,38,39,],[7,13,14,13,-7,-10,-12,-13,13,13,13,13,13,13,-11,13,13,13,13,13,-5,-6,-8,-9,]),'num':([4,8,10,11,12,13,14,17,19,20,21,24,25,26,27,28,29,33,36,37,38,39,],[12,12,-7,-10,-12,-13,12,12,12,12,12,12,-11,12,12,12,12,12,-5,-6,-8,-9,]),')':([6,7,9,10,11,12,13,18,23,25,31,32,34,35,36,37,38,39,],[15,16,22,-7,-10,-12,-13,25,30,-11,36,37,38,39,-5,-6,-8,-9,]),'ADD':([8,],[17,]),'SUB':([8,],[19,]),'MUL':([8,],[20,]),'DIV':([8,27,],[21,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Comando':([0,],[1,]),'Exp':([4,8,14,17,19,27,33,],[9,18,23,24,26,18,18,]),'Termo':([4,8,14,17,19,20,21,24,26,27,33,],[10,10,10,10,10,28,29,31,32,10,10,]),'Fator':([4,8,14,17,19,20,21,24,26,27,28,29,33,],[11,11,11,11,11,11,11,11,11,11,34,35,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Comando","S'",1,None,None,None),
  ('Comando -> ( READ id )','Comando',4,'p_Comando_ler','sexp_yacc.py',8),
  ('Comando -> ( PRINT Exp )','Comando',4,'p_Comando_escrever','sexp_yacc.py',13),
  ('Comando -> ( SET id Exp )','Comando',5,'p_Comando_atrib','sexp_yacc.py',17),
  ('Comando -> ( DUMP )','Comando',3,'p_Comando_despejar','sexp_yacc.py',21),
  ('Exp -> ( ADD Exp Termo )','Exp',5,'p_Exp_add','sexp_yacc.py',25),
  ('Exp -> ( SUB Exp Termo )','Exp',5,'p_Exp_sub','sexp_yacc.py',29),
  ('Exp -> Termo','Exp',1,'p_Exp_termo','sexp_yacc.py',33),
  ('Exp -> ( MUL Termo Fator )','Exp',5,'p_Termo_mul','sexp_yacc.py',37),
  ('Termo -> ( DIV Termo Fator )','Termo',5,'p_Termo_div','sexp_yacc.py',41),
  ('Termo -> Fator','Termo',1,'p_Termo_fator','sexp_yacc.py',49),
  ('Fator -> ( Exp )','Fator',3,'p_Fator_group','sexp_yacc.py',53),
  ('Fator -> num','Fator',1,'p_Fator_num','sexp_yacc.py',57),
  ('Fator -> id','Fator',1,'p_Fator_id','sexp_yacc.py',61),
]
