
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "numABin : '(' num ABin ABin ')'ABin : '(' ')'"
    
_lr_action_items = {'(':([0,3,4,5,7,],[2,2,-2,2,-1,]),'$end':([1,4,7,],[0,-2,-1,]),'num':([2,],[3,]),')':([2,4,6,7,],[4,-2,7,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ABin':([0,3,5,],[1,5,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ABin","S'",1,None,None,None),
  ('ABin -> ( num ABin ABin )','ABin',5,'p_ABin','abin_yacc.py',23),
  ('ABin -> ( )','ABin',2,'p_ABin_empty','abin_yacc.py',27),
]
