
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'um zeroCapicua : zero ContZCapicua : um ContUCapicua : ContZ : Capicua zeroContZ : ContU : Capicua umContU : '
    
_lr_action_items = {'zero':([0,2,3,4,5,6,8,9,],[2,2,2,-1,8,-2,-4,-6,]),'um':([0,2,3,4,6,7,8,9,],[3,3,3,-1,-2,9,-4,-6,]),'$end':([0,1,2,3,4,6,8,9,],[-3,0,-5,-7,-1,-2,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Capicua':([0,2,3,],[1,5,7,]),'ContZ':([2,],[4,]),'ContU':([3,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Capicua","S'",1,None,None,None),
  ('Capicua -> zero ContZ','Capicua',2,'p_Capicua_zeros','capicua_binaria2_yacc.py',6),
  ('Capicua -> um ContU','Capicua',2,'p_Capicua_uns','capicua_binaria2_yacc.py',10),
  ('Capicua -> <empty>','Capicua',0,'p_Capicua_vazio','capicua_binaria2_yacc.py',14),
  ('ContZ -> Capicua zero','ContZ',2,'p_ContZ_zero','capicua_binaria2_yacc.py',18),
  ('ContZ -> <empty>','ContZ',0,'p_ContZ_vazia','capicua_binaria2_yacc.py',22),
  ('ContU -> Capicua um','ContU',2,'p_ContU_um','capicua_binaria2_yacc.py',26),
  ('ContU -> <empty>','ContU',0,'p_ContU_vazia','capicua_binaria2_yacc.py',30),
]
