
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "FLOAT ID INT SEPLista : SeccoesSeccoes : Seccoes SeccaoSeccoes : Seccao : ID ':' ProdutosProdutos : ProdutoProdutos : Produtos ProdutoProduto : '-' INT SEP ID SEP FLOAT SEP INT ';'"
    
_lr_action_items = {'ID':([0,2,3,6,7,9,11,17,],[-3,4,-2,-4,-5,-6,12,-7,]),'$end':([0,1,2,3,6,7,9,17,],[-3,0,-1,-2,-4,-5,-6,-7,]),':':([4,],[5,]),'-':([5,6,7,9,17,],[8,8,-5,-6,-7,]),'INT':([8,15,],[10,16,]),'SEP':([10,12,14,],[11,13,15,]),'FLOAT':([13,],[14,]),';':([16,],[17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Lista':([0,],[1,]),'Seccoes':([0,],[2,]),'Seccao':([2,],[3,]),'Produtos':([5,],[6,]),'Produto':([5,6,],[7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Lista","S'",1,None,None,None),
  ('Lista -> Seccoes','Lista',1,'p_Lista','lista_compras_yacc.py',8),
  ('Seccoes -> Seccoes Seccao','Seccoes',2,'p_Seccoes_seccao','lista_compras_yacc.py',13),
  ('Seccoes -> <empty>','Seccoes',0,'p_Seccoes_empty','lista_compras_yacc.py',18),
  ('Seccao -> ID : Produtos','Seccao',3,'p_Seccao','lista_compras_yacc.py',23),
  ('Produtos -> Produto','Produtos',1,'p_Produtos_produto','lista_compras_yacc.py',27),
  ('Produtos -> Produtos Produto','Produtos',2,'p_Produtos_produtos','lista_compras_yacc.py',31),
  ('Produto -> - INT SEP ID SEP FLOAT SEP INT ;','Produto',9,'p_Produto','lista_compras_yacc.py',35),
]
